theme: jekyll-theme-hacker
# header text

title: Bash_Shell_Scripting
description: BASH where there is a shell, there is a way
author_email: eliasnievap@protonmail.com
url: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/

compass:
 logo: "logo_grupo.jpg"
 author: "Elias Nieva"
 tagline: "BASH where there is a shell, there is a way"
 include_content: true

collections:
  my_collection:
    output: true

defaults:
  -
    scope:
      path: "section/*/special-page.html"
    values:
      layout: "specific-layout"
