theme: jekyll-theme-hacker
# header text
title: Bash_Shell_Scripting
description: BASH where there is a shell, there is a way
author_email: eliasnievap@protonmail.com

compass:
 logo: "logo_grupo.jpg"
 author: "Elias Nieva"
 tagline: "BASH where there is a shell, there is a way"
 include_content: true

# Variables

url: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/
ejer: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/ejercicios.html
tuto: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/Test/scripts.html
docu: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/Documentacion/Indice_Libros.html
admins: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/administradores.html
telegram: https://t.me/shell_cli_bash_scripting
Twitter: https://twitter.com/EliasNieva
Mastodon: https://mastodon.social/@EliasNieva
GitHub: https://github.com/EliasNP
Mail]: mailto:eliasnieva@keemail.me

# Imagenes

img_telegram: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/imag/telegram.png
img_twitter: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/imag/twitter.png
img_mastodon: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/imag/mastodon.png
img_github: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/imag/github.png
img_mail: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/imag/Mail-icon.png
imb_creative: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/imag/88x31.png
img_tux: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/imag/tux.png
img_terminal: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/imag/terminal.png
img_rss: https://eliasnp.github.io/t.me-shell_cli_bash_scripting/imag/rss.png
